### PR TITLE
Isoform Override support

### PR DESCRIPTION
**Pull request by onursumer**
This PR adds support for isoform overrides:

- From the **/variant_annotation/isoform_override** service, isoform information for certain transcripts (from a specific override source) can be requested.
- **/variant_annotation/hgvs** now accepts an optional parameter **isoformOverrideSource**. When **isoformOverrideSource** is provided, this service takes isoform override information into account and enriches the returned JSON with the overridden canonical isoform information. Currently, enriched JSON is not saved back to the cache.

This service requires an additional line in application.properties, an example:
<code>vep.overrides_uris=uniprot=isoform_overrides_uniprot,mskcc=isoform_overrides_mskcc</code>

For an example isoform override file resource, see https://github.com/mskcc/vcf2maf/blob/master/data/isoform_overrides_uniprot

### CODE REVIEW

**Comment by n1zea144** [comment]
Should we move the AnnotationEnricher and IsoformAnnotationEnricher into the service package?

**Comment by onursumer** [comment]
We can also consider moving them into a new separate package. But for now, I think service package seems like a better place than domain package.

**Comment by onursumer** [comment]
@n1zea144 @jjgao @zheins : do you think this PR is ready to merge?

**Comment by zheins** [comment]
I've been using this branch in my development of the pipeline, seems to be working

**Comment by jjgao** [comment]
I just merged it :)

**Comment by onursumer** [comment]
Thanks jj!

**Pull request merged**
